### ISSUE TITLE
`NockStack` guard page

### ISSUE THREAD

**Issue by ashelkovnykov** [urbit/ares#150]
The `NockStack` should have a guard page for safety and so that we can detect OOM errors during computation. Currently, there's no defense against the two stacks in 2Stackz clobbering each other.

**Comment by eamsden** [comment]
per discussion with @ashelkovnykov and I believe originally due to @joemfb: we are going to put a Nockstack OOM (bail:meme) check in the allocation routines. The guard page will also be implemented but will simply attempt to recenter, and rethrow the SIGSEGV if it cannot. This will be a security and debugging measure only and should never occur in normal pier operation.

**Comment by ashelkovnykov** [comment]
Resovled by #211 and #202
